gitlabUrl: ""
runnerRegistrationToken: ""
## For RBAC support:
rbac:
  create: true
  clusterWideAccess: true

runners:
  config: |
    [[runners]]
      excutor = "kubernetes"
      [runners.kubernetes]
        image = "ubuntu:18.04"
        [[runners.kubernetes.volumes.host_path]]
          name = "docker"
          mount_path = "/var/run/docker.sock"
          host_path = "/var/run/docker.sock"
        [[runners.kubernetes.host_aliases]]
          ip = ""
          hostnames = ["harbor.or.kr"]

